# Site settings
title:  Romina Caraba-Thampi
email:  romina.caraba@gmail.com
description: Data Scientist passionate about health, wellbeing and environment.
#>  this means to ignore newlines until "baseurl:"

baseurl:  https://rominacarabathampi.github.io/ # the subpath of your site, e.g. /blog/
url:  https://rominacarabathampi.github.io/ # the base hostname & protocol for your site

github_username:  rominacarabathampi
linkedin: rominacaraba
github-url: rominacarabathampi
# Build settings
markdown: kramdown
